### ISSUE TITLE
Add Ubuntu support

### ISSUE THREAD

**Issue by jkroepke** [lelutin/puppet-fail2ban#35]
Since Ubuntu and Debian are really the same, best effort support for ubuntu would be fine.

- or -

Don't fail if ubuntu is used.

**Comment by lelutin** [comment]
I'll add this in, yes! what I can do now that I've integrated test (*ahem*.. there needs to be more tests hehe) into travis.ci, I can request that tests be run on some current releases of ubuntu, also.

I'd probably target LTS releases for support, but the module itself would not refuse to work on non-lts


I'm slowly working my way to transforming fail2ban::jail::* before releasing 3.0.0 -- I'm currently placing things and testing out removing all fail2ban::jail::* classes and putting the default parameters for them into a module hiera.yaml. So I'll work on adding support for ubuntu after this change
If you feel comfortable adding test runs in `.travis.yaml`, implementing support in the different case blocks where it currently fails and adding ubuntu support to metadata.json I'd gladly merge this in! otherwise no problem, I'll get to it soon enough

**Comment by jkroepke** [comment]
Sure.

If your target in 3 is only Debian 9, you probably want to support 18.04 only.

**Comment by lelutin** [comment]
ah right because bionic beaver is the first release with puppet 4.x.

**Comment by jkroepke** [comment]
Nah. There is puppet 4 and 5 support for 16.04, too. You just have to use upstream puppet

**Comment by lelutin** [comment]
sure, you can do this with debian wheezy and jessie too.
I know I'm a heretic in this world of fast development but I personally don't like to install stuff from 3rd party repositories. I'm open to removing some condition checks in the module and add parameters for changing config paths or templlates if it makes it possible to use upstream packages with releases that the module currently doesn't support, but by default I support OS releases and so what packages come with them too.

**Comment by jkroepke** [comment]
> I personally don't like to install stuff from 3rd party repositories.

Thats totally fine and in a company you wouldn't do this, too. But do not block/restrict the users that wanna do this.

**Comment by jcharaoui** [comment]
Does it fail because Ubuntu is missing from `metadata.json`? Otherwise, the manifests should compile on Ubuntu since `$facts['osfamily']` should be set to "Debian" on Ubuntu.

**Comment by lelutin** [comment]
@jcharaoui, @jkroepke  now that pre-defined jails are on master, as promised we can work on ubuntu.

my suggestion is to add ubuntu to the matrix of tested systems in the `.travis.yml` file and see what the test results are (fwiw... the tests are very simplistic, but at least it should tell us if some unsupported feature is used). if there's anything failing then we can fix it, and then add ubuntu to `metadata.json`

**Comment by lelutin** [comment]
hmm actually if I understand correctly, travis-ci already uses ubuntu:

https://docs.travis-ci.com/user/reference/overview/

I've just added it to metadata.json in cc0e477

@jkroepke : I think normally the module should not error out when using ubuntu, since the only check for compatibility is made with `$facts['os']['family']` and anything in the debian family is accepted.

also, "official" support is for 18.04 since it ships puppet 4.x, but if you're using upstream repositories for running puppet 4.x or 5.x on older releases of ubuntu, I think the module should work for you, provided the fail2ban version is recent enough (for example trusty ships fail2ban 0.8.11 which is somewhat old).

please make a sign here if you're having issues when using the module. I'll keep this issue opened for two months before closing, just to make sure you have some time to respond.

**Comment by jkroepke** [comment]
Hi,

since the situation was not clear for me moved to an other module.

You are right, the module should not fail. I was wrong.

Thanks for your work.


Am 20.06.2018 um 09:00 schrieb Gabriel Filion <notifications@github.com>:

hmm actually if I understand correctly, travis-ci already uses ubuntu:

https://docs.travis-ci.com/user/reference/overview/

I've just added it to metadata.json in cc0e477
<https://github.com/lelutin/puppet-fail2ban/commit/cc0e477140fdd4e099be4977e3db52f2412061ff>

@jkroepke <https://github.com/jkroepke> : I think normally the module
should not error out when using ubuntu, since the only check for
compatibility is made with $facts['os']['family'] and anything in the
debian family is accepted.

also, "official" support is for 18.04 since it ships puppet 4.x, but if
you're using upstream repositories for running puppet 4.x or 5.x on older
releases of ubuntu, I think the module should work for you, provided the
fail2ban version is recent enough (for example trusty ships fail2ban 0.8.11
which is somewhat old).

please make a sign here if you're having issues when using the module. I'll
keep this issue opened for two months before closing, just to make sure you
have some time to respond.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lelutin/puppet-fail2ban/issues/35#issuecomment-398645269>,
or mute the thread
