### ISSUE TITLE
Add support for Centos/Redhat 8

### ISSUE THREAD

**Issue by xhejtman** [lelutin/puppet-fail2ban#43]
class fail2ban::config {

   if $facts['os']['release']['major'] == '8' {

I suppose, this is meant for debian 8 only, but it collides with Centos 8, so should be fixed like:
if $facts['os']['release']['major'] == '8' and $facts['os']['family'] == 'Debian' {

**Comment by lelutin** [comment]
ah yes you're right!

I've pushed cd0635a76f656705d199a12940f44b9034274749 and 8bb58c97b9595ddef709b1590a0073bf393dceee (since I forgot one if block in the first commit) which should make sure that centos/redhat 8 don't use debian jessie hacks.

I'm tentatively adding support for version 8 of those distros in metadata.json. If you encounter any other bug, let me know :)
