### ISSUE TITLE
BUG: Requirements for  $logpath makes it impossible to set $backend to 'systemd' 

### ISSUE THREAD

**Issue by sigurdurdahl** [lelutin/puppet-fail2ban#50]
Hi,

I think the changes done in 50327e1c6361bedf5dee361f48570c3be6d63555 by @jkroepke introduces a bug.

Line 112 now requires that logpath is set
```
Variant[String, Array[String]] $logpath            = [],
```

while the if block at line 127 requires logpath to be unset if backend is systemd:
```
if $backend == 'systemd' {
    if $logpath {
      fail('logpath must not be set when $backend is \'systemd\'')
    }
  }
```

At least I have been unable to find a value for logpath that combines with systemd as chosen backend after my last upgrade of puppet-fail2ban. Workaround for now is using an older version.

Thanks in advance for looking into this!

Br,
Sigurd

**Comment by lelutin** [comment]
oh wow that is a weird property of arrays.. I was also expecting `if $array {` to be "false-ish".

I can see that puppet 5.5.0 has introduced a new builtin function `empty()` (which was available in stdlib before that) that we can use in this manner:

~~~
$foo = []

if ! empty($foo) {
  notice('foo is true')
}
~~~

I'll patch that up real quick. thanks for catching that and notifying us!

**Comment by lelutin** [comment]
@sigurdurdahl I've pushed a commit that had a mention of closing this issue. from my own testing I believe that the issue is fixed, however I'd like to also get your confirmation if this is true before I make a new forge release for the module.

note that I've also expanded the data type change made by @jkroepke to the `logpath` param on the module's main class. This way the data types are consistent for the same setting whether it's made on the global scope or on individual jails.

I'll await for your feedback regarding the fix!

**Comment by sigurdurdahl** [comment]
Sorry for the late reply @lelutin !

I can confirm that this resolves the issue. Thank you!

**Comment by lelutin** [comment]
> Sorry for the late reply @lelutin !

there's no issue at all, we can't always be in front of github ready to respond, right? ;)   actually I think your response was pretty quick hehe.

> I can confirm that this resolves the issue. Thank you!

great, thanks for testing it out!

I'll try and find some time soon to make a release of the module then.
