### ISSUE TITLE
sshd jail fails on Ubuntu 20.04 (is this module maintained?)

### ISSUE THREAD

**Issue by tobixen** [lelutin/puppet-fail2ban#56]
Rolling out the module according to the README on Ubuntu 20.04 just for protecting sshd causes a broken fail2ban ... the service fails with the error message:

```
fail2ban                [878455]: ERROR   Failed during configuration: Have not found any log file for sshd jail
```

I can probably figure out of this and make a pull request, but first I'd like to know if this module is maintained, and if it is supposed to work with Ubuntu?  The alternative seems to be the voxpupuli-module, but it seems like it's a lot more work to set up a simple sshd jail with the voxpupuli-module.

**Comment by tobixen** [comment]
Replacing

```
logpath = %(sshd_log)s
backend = %(sshd_backend)s
```

with

```
backend = systemd
```

in `/etc/fail2ban/jail.d/sshd.conf` seems to help.  `backend = systemd` seems like a sane default for most modern distros.

It should be trivial to come up with a pull request for this one ... though I'd like feedback on if it will be merged before I start working on it.

**Comment by tobixen** [comment]
Looking more into the fail2ban configuration, the `sshd_backend` is configured to be a `default_backend` ... which was not touched by the fail2ban module.  And the default sshd configuration in the package is the same as what was rolled out by this fail2ban-module.  Perhaps the problem is actually in the fail2ban package, and not in the puppet module.

**Comment by tobixen** [comment]
I purged the config, reinstalled the package, and enabled the sshd jail according to the instructions supplied in the jail.conf file from the package - and fail2ban fails to start.  I conclude that the problem is in the fail2ban package for ubuntu, not in this puppet module as such.  Probably it will work if installing a syslog package.

I will leave this issue open - I think that with a good puppet module things should "just work" - even if that means adding workarounds for known bugs in the package. :-)

**Comment by tobixen** [comment]
Found some relevant issues:

https://bugs.launchpad.net/ubuntu/+source/fail2ban/+bug/1696591
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770171

So in the default `/etc/fail2ban/jail.conf` the default backend is set to systemd.  Since jail.conf is maintained by this puppet module, I've concluded that the issue should be addressed by this puppet module, regardless of how it's solved upstream.

Setting the default backend to systemd may not be the correct approach, as it will break for services that uses log files without explicitly giving a backend.

**Comment by tobixen** [comment]
Syslog can be installed as a separate package.  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770171 hints that this may be an issue on Debian too ... all since 2014 indeed :-)  The bug report I found for Ubuntu tells me it has been an issue also for ubuntu 16.04 (but we do have several ubuntu 16.04-instances with your puppet module running where it hasn't been an issue ... perhaps our 16.04 base image came with syslog installed, I should check that up).  This will definitively continue being an issue in 22.04, unless the problem is fixed upstream.

I'll think a bit more on this until tomorrow.

**Comment by tobixen** [comment]
I should add, this is not specific for Ubuntu, this is the general directions things are going in several distributions.  I'll check up a bit how things are working on centos and archlinux as soon as I get the time for it.

**Comment by tobixen** [comment]
I've raised an issue upstream: https://github.com/fail2ban/fail2ban/issues/3292

**Comment by tobixen** [comment]
@lelutin , could you check if my hypotheses are correct also for your Debian ...

* It does use systemd
* information from ssh, postfix, proftpd, wuftp, dropbear, etc does end up in the journal?

I don't think it's a point to check all those services ... just do `sudo journalctl -f` and try to ssh into it.

**Comment by lelutin** [comment]
Hi again @tobixen and thanks for all of the analysis.

So far the approach that I've used for this puppet module is to make sure that default configurations in distros/releases are supported out of the box by the module, and it should be possible to set options to make it configure things when a different setup is used.

So.. if I understand the situation properly, do you mean that ubuntu's default configuration (e.g. a fresh vanilla install of ubuntu) replaced syslog with journald entirely starting with a certain version (maybe 20.04? or maybe before?). I know that debian has still not moved to replace syslog with journald, but it's quite possible that ubuntu made the move.
If that's the case, then we can add some overrides in this module in order to accomodate this change.

One method is to override the default backend param. The module has a `backend` param on the main class that sets the default backend. So we could override that parameter via hiera where necessary -- e.g. we could have a default case in `Ubuntu.yaml` that would reflect the new configuration of using systemd as the backend, and then add `Ubuntu-18.yaml` with an override to set the bakend back to `auto` and then copy this to other `Ubuntu-X.yaml` files for the other supported versions of ubuntu that still were using syslog by default.

Do you think this method would work sufficiently well for you and other users? If you want to try it out, you can create a file `data/Ubuntu-20.yaml` in the module on your puppet server with content like this:

~~~yaml
---
fail2ban::backend: 'systemd'
~~~


This'll set the backend only for 20.04. If this works properly we can create the files in the module in the "reverse order" as described above (e.g. create the above content in `data/Ubuntu.yaml` instead, and then add similar content for `data/Ubuntu-18.yaml` and `data/Ubuntu-16.yaml` but with `auto` instead of `systemd`.


Also, by looking at things for this issue, I saw that management of `paths-*` should have been removed with removal of debian jessie support, so I created #57 to sidestep that issue in its own place.

**Comment by lelutin** [comment]
oh wait I think I got confused a bit (it's a bit hard for me to visualize what's happening without a local ubuntu VM -- I should just download an image to check things out).

iiuc the current value within the `paths-*` file is something like:

~~~ini
default_backend = %(default/backend)s

sshd_backend = %(default_backend)s
~~~

is this it?

if that's the case then I believe it means that with `%(default/backend)s` it is grabbing the default backend set in `jail.conf` in the default section. So in that case the difference that would be an issue for your case would be the value in jail.conf and setting `fail2ban::backend` to the value `systemd` should make your setup work properly (e.g. there's no weirdness happening with management of the `paths-*` files since the module is apparently not managing them at all)

Sorry if I sounded maybe a bit confused in my previous message. But as I said in the previous message, if ubuntu did change the default backend for logs from syslog to journald starting with 20.04 we should apply a fix with hiera as described previously.

Cheers

**Comment by tobixen** [comment]
Unfortunately the fail2ban setup got pushed further down in my todo-stack, I'm not sure I will get time to revisit this one until the autumn.  If I remember correct, the ubuntu image I had would only log things like sshd into the journal and not into log files.  I do not know if this is specific for the ubuntu image I had access to or if it applies generally.  As far as I can understand, Debian can also be configured that way, as I found an old bug report on this applying to Debian.

**Comment by lelutin** [comment]
I've just reviewed this to see if I can push things forward somehow and here's what I've come to understand:

* the default `paths-*` file, which are not managed by this module, define sshd's backend as `default/backend`. This resolves to the value of the `backend` option set in the `default` section in `jail.conf` which by default is set to `auto`
* older versions of the fail2ban package only had `python3-systemd` as a `Recommends` so it was not installed simultaneously with fail2ban. This lack of the library in turn makes fail2ban's `auto` backend skip over systemd
* the debian bug report linked in the ubuntu bug report in the initial message says that `python3-systemd` was changed into a `Depends` instead, so the library should install automatically.

@tobixen it's been a while since we've both touched this issue, but if you happen to still have ubuntu hosts with fail2ban, could you try something out? I'm wondering if you repeat your test of installing fail2ban manually and setting up the sshd jail as recommended in jail.conf, but if you also `apt install python3-systemd`: do you correctly get fail2ban to use the systemd backend? once fail2ban is running you can check this out with `fail2ban-client get sshd backend`

from what I can see, the package dependency for python3-systemd only appears as a Depends in 24.04 : https://packages.ubuntu.com/noble/fail2ban -- so if the above seems to work, we'll also have to use the workaround for 22.04. what we can do in the module in that case is to conditionally explicitly install `python3-systemd`

ubuntu 20.04 will still be in extended LTS until 2028 and 22.04 for even longer so it seems worth it to create a workaround in the module to get things working properly

in contrast, in debian the Depends relationship only appears in current testing (trixie, future debian 13), but up to bookworm (12) debian has not made an official switch from syslog to journald for system-wide logging. that will only happen in trixie. so there's no workaround necessary for debian.

**Comment by lelutin** [comment]
I've just run some testing in an ubuntu 22.04 VM and I wasn't able to reproduce the issue. from what I can see python3-systemd comes in already installed as a dependency to apport.

also fail2ban was running fine after running this module and setting up the default sshd jail

the above also held true for ubuntu 20.04

...so I'm unable to reproduce. I'll close because of that, but feel free to reopen if you can bring up a short method for reproducing the bug.

p.s.: I *have* seen something similar to this but in a docker container based on ubuntu 18.04. that was happening because (expectedly for a base container) systemd is not installed in there so the default log backend should not be set to systemd. I don't believe this matches the case you described earlier though.
